apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app-deployment
spec:
  selector:
   matchLabels:
    app: python-app
  replicas: 1
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
        - name: python-app
          image: renatoapaza/python-app:3.udi
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
              name: python-app-port
---
apiVersion: v1
kind: Service
metadata:
  name: python-app-service
  labels:
    app: python-app
spec:
  type: LoadBalancer
  #type: NodePort
  ports:
  - name: python-app
    port: 5000
    #nodePort : 30007 
  selector:
   app: python-app